### ISSUE TITLE
Error when accessing History data for Melbourne Museum 

### ISSUE THREAD

**Issue by josh-js** [josh-js/Melbourne-History-Mobile#13]
On clicking the Place marker for **Melbourne Museum**, the following error is produced.

APP_VERSION_CODE=1
APP_VERSION_NAME=1.0
ANDROID_VERSION=5.1.1
PHONE_MODEL=SM-G925I
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: length=61708; regionStart=15047; regionLength=-47
at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6843)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.StringIndexOutOfBoundsException: length=61708; regionStart=15047; regionLength=-47
at java.lang.String.startEndAndLength(String.java:504)
at java.lang.String.substring(String.java:1333)
at android.melbournehistorymap.MapsActivity$2$1$1.onSuccess(MapsActivity.java:343)
at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
... 8 more
java.lang.StringIndexOutOfBoundsException: length=61708; regionStart=15047; regionLength=-47
at java.lang.String.startEndAndLength(String.java:504)
at java.lang.String.substring(String.java:1333)
at android.melbournehistorymap.MapsActivity$2$1$1.onSuccess(MapsActivity.java:343)
at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6843)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by josh-js** [comment]
Another error for **University of Melbourne**

APP_VERSION_CODE=1
APP_VERSION_NAME=1.0
ANDROID_VERSION=5.1.1
PHONE_MODEL=SM-G925I
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: java.lang.StringIndexOutOfBoundsException: length=254002; regionStart=19064; regionLength=-4064
at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6843)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: java.lang.StringIndexOutOfBoundsException: length=254002; regionStart=19064; regionLength=-4064
at java.lang.String.startEndAndLength(String.java:504)
at java.lang.String.substring(String.java:1333)
at android.melbournehistorymap.MapsActivity$2$1$1.onSuccess(MapsActivity.java:343)
at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:351)
