### ISSUE TITLE
Android 6.0.* Crash

### ISSUE THREAD

**Issue by josh-js** [josh-js/Melbourne-History-Mobile#44]
Still crashes on v0.3-alpha release

Need to try and get my hands on an Android v6 phone..

**Comment by josh-js** [comment]
Found a API 23 Android 6 Emulator.. trying to run it now, but my laptop is grinding to a halt

**Comment by josh-js** [comment]
Thanks to people at work, have pointed me to this emulator
https://www.genymotion.com/#!/developers

**Comment by josh-js** [comment]
android.melbournehistorymap fatal error : Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                       java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
                                           at android.melbournehistorymap.MainActivity$1.onClick(MainActivity.java:43)
                                           at android.view.View.performClick(View.java:5198)
                                           at android.view.View$PerformClick.run(View.java:21147)
                                           at android.os.Handler.handleCallback(Handler.java:739)
                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                           at android.os.Looper.loop(Looper.java:148)
                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                           at java.lang.reflect.Method.invoke(Native Method)
                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by josh-js** [comment]
Location mLastLocation was coming up null.. Looks like after the request permission is accepted, the user is never sent to the onConnect() override, so Location is never initiated.

Making changes and testing

**Comment by josh-js** [comment]
http://android-developers.blogspot.com.au/2015/09/google-play-services-81-and-android-60.html

**Comment by josh-js** [comment]
Emulator is having issues support Google Maps and GPS location services, which is making it just as hard to test with.

Tempted to say I just wont support it for the purpose of this project.. (What did our initial report state?)

**Comment by josh-js** [comment]
Made some changes, untested, but does not seem to impact API22.. see how it goes with API23
