### ISSUE TITLE
Get Latitude and Longitude returning Null

### ISSUE THREAD

**Issue by josh-js** [josh-js/Melbourne-History-Mobile#56]
APP_VERSION_CODE=1
APP_VERSION_NAME=1.0
ANDROID_VERSION=5.0
PHONE_MODEL=SM-G900I
CUSTOM_DATA=
STACK_TRACE=java.lang.IllegalStateException: Could not execute method for android:onClick
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:275)
at android.view.View.performClick(View.java:5156)
at android.view.View$PerformClick.run(View.java:20755)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5832)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:270)
... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
at android.melbournehistorymap.MainActivity.openMapView(MainActivity.java:229)

**Comment by josh-js** [comment]
seems to be working fine now. I deleted all traces of it, went through my settings for unknown installs first, turned on location services and turned off wifi just incase someone is torrenting and now it seems to be working really well

**Comment by josh-js** [comment]
Added a check for Location Services and method to Restart activity
