### ISSUE TITLE
GMS Activity failed to start on Android API Level 16

### ISSUE THREAD

**Issue by josh-js** [josh-js/Melbourne-History-Mobile#8]
01-02 14:21:32.308 22235-22235/android.melbournehistorymap E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             java.lang.RuntimeException: Unable to get provider com.google.android.gms.measurement.AppMeasurementContentProvider: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurementContentProvider
                                                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:4663)
                                                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4290)
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4232)
                                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:140)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                 at android.os.Looper.loop(Looper.java:137)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4921)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
                                                                                 at dalvik.system.NativeStart.main(Native Method)
                                                                              Caused by: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurementContentProvider
                                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                                 at android.app.ActivityThread.installProvider(ActivityThread.java:4648)
                                                                                 at android.app.ActivityThread.installContentProviders(ActivityThread.java:4290) 
                                                                                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4232) 
                                                                                 at android.app.ActivityThread.access$1400(ActivityThread.java:140) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1297) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                 at android.os.Looper.loop(Looper.java:137) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:4921) 
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                 at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) 
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) 
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by josh-js** [comment]
Seems to be a method limitation on API levels less than 21.

https://developers.google.com/android/guides/setup#split
